from waflib.Configure import conf

def options(opt):
    pass


def build(bld):
    bld(features='cxx cxxprogram',
        source='main.cpp',
        includes='. ../../src',
        target='myExp',
        uselib='BOOST EIGEN TBB LIBCMAES NLOPT',
        use='limbo')